version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: node-vue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "node-vue", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:mypassword@postgres:5432/node-vue
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
